name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Zip the Build
      run: 7z a -tzip ./BluetoothAudioCodecInspector.zip ./BluetoothAudioCodecInspector/bin/Release/net6.0/
      

    - name: GH Release
      # You may pin to the exact commit or the version.
      # uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
      uses: softprops/action-gh-release@v0.1.15
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        body: build
        # Gives a tag name. Defaults to github.GITHUB_REF
        tag_name: 0.1
        # Creates a draft release. Defaults to false
        draft: false
        # Newline-delimited list of path globs for asset files to upload
        files: ./BluetoothAudioCodecInspector.zip
        # Authorized secret GitHub Personal Access Token. Defaults to github.token
        token: ${{ secrets.GH_TOKEN }}
        # Whether to automatically generate the name and body for this release. If name is specified, the specified name will be used; otherwise, a name will be automatically generated. If body is specified, the body will be pre-pended to the automatically generated notes.
        #generate_release_notes: true
